### ISSUE TITLE
backpack wont open

### ISSUE THREAD

**Issue by wozmon** [talonos2/BlightfallTracker#100]
when ive equipped my backpack to my back i cannot find a way to open it,i have remapped the shortcut key and it still wont open, i also cant take it off my back.

**Comment by talonos2** [comment]
Sneak click the ground with an empty hand to take it off. You can then
access the backpack as though it were a chest. You cannot access the
contents of your backpack while it is worn. This is a design decision made
by better storage to simulate how real backpacks work. (Ever try taking
something out of a backpack while wearing it? It's pretty hard.)

If this annoys you, consider a TiC "Knapsack" instead. I hear they are a
little more intuitive.

**Comment by wozmon** [comment]
thanks, this really helped
