### ISSUE TITLE
Dawn Machine not deactivating with redstone. 

### ISSUE THREAD

**Issue by LordQ42** [talonos2/BlightfallTracker#101]
I have a dawn machine set up, with pipes providing essentia from warded jars. If I apply redstone to the center block, the lights on the machine turn off (the eyes go from green to dark) but it continues to consume essentia. (if you're running on a clean part of the world, it eats Ordo and Cognitio at a frightening pace, about 1 a second. )

**Comment by Jonas-V-Nielsen** [comment]
You presumably have your energy cube's redstone interaction set to 'Low', making it starve the Dawn Machine of power (Glowing eyes = Powered) whenever you apply redstone to the cube.
I'm assuming your cube is attached to the machine, and catches the signal applied to it.

Not being able to turn the machine off- coupled with it consuming virtually all available cognitio, machina and ordo once an area has been cleared sure makes it a very high-maintenance project.

To reiterate:
Can't turn off Dawn Machine.
Excessive resource consumption when not cleaning.
