### ISSUE TITLE
2.1.2 Server hangs

### ISSUE THREAD

**Issue by Protector152** [talonos2/BlightfallTracker#103]
server hangs in initial startup/setup after "Successfully generated Thyrork.schematic."
link to logs follow

https://gist.github.com/Protector152/ec8c4f53d0f6a7be5266

Loving the modpack so far. thanks for any / all help

**Comment by talonos2** [comment]
That is the last thing that should pop up before you begin on a new world. In fact look up several lines:

"[17:52:54] [Server thread/INFO]: Done (4.178s)! For help, type "help" or "?""

You should be able to log in and play. The server is up as far as your logs show.

Comment if you still need help.
