### ISSUE TITLE
Cannot make diamond sword with blood magic alchemical set

### ISSUE THREAD

**Issue by LordQ42** [talonos2/BlightfallTracker#104]
I have been following the dark one quest line, I created the alchemical chemistry set, and now need to make the diamond sword. I put the two diamonds and a stick in the set, even added in a charged blood orb and still can't get a sword out of it. am I just missing something here?

**Comment by talonos2** [comment]
I had to change the recipe last update to make diamond pickaxes craftable,
and forgot to update the quest text. Use NEI to find the new recipe. This
will be fixed next version.
