### ISSUE TITLE
Incorrect world gen on server

### ISSUE THREAD

**Issue by RamasesN3** [talonos2/BlightfallTracker#105]
I downloaded and ran the server on my personal Ubuntu box.  It all seemed fine, it ran without errors.
However when I connected to the server there was no space ship but I spawned at high altitude and fell to my death.

Is there a setting that should be in the server.properties that isn't in there by default?

**Comment by talonos2** [comment]
No, it works fine on a fresh unzip on many other people's experience. Besides telling you that it's not loading the included world file, I'm not sure where to start trying to help. Is there any reason why it would not be loading from the included /world directory?

**Comment by RamasesN3** [comment]
tried it a few time with the same result.  In the end I created a single player world and then copied the world save to the sever and I'm all good.
