### ISSUE TITLE
Scrolling through Cooking Table disables ability to craft with Cooking Table.

### ISSUE THREAD

**Issue by Moleculor** [talonos2/BlightfallTracker#107]
The ability to craft food through the crafting interface of the Cooking Table is only present/available so long as the scrollbar in the table is scrolled all the way to the top. Scrolling down even slightly disables the ability to click a second time to craft the item. Scrolling back up to the top restores it. 

I can't tell if this is a Blightfall specific issue or a Cooking for Blockheads issue.

**Comment by AKA-Syenite** [comment]
Source of this is https://github.com/blay09/CookingForBlockheads/commit/d1913c095bde024647844e4ab5a4e8904e56ef61 which was the fix for https://github.com/blay09/CookingForBlockheads/issues/46

**Comment by Moleculor** [comment]
Odd, since that bug report references the mouse wheel, and this bug shows up even when I grab the scrollbar with my left mouse button and move it down/up.

**Comment by talonos2** [comment]
Solved by upgrading C4B
