### ISSUE TITLE
Missing Floating islands in Jaded Map room

### ISSUE THREAD

**Issue by LordQ42** [talonos2/BlightfallTracker#108]
Floating Island is not on the progress bars, but Archipelago is up there twice.

**Comment by talonos2** [comment]
How embarrassing. How did we not notice this?

An op can right-click the little picture of the biome above the progress bar with an empty hand to change which biome that bar represents. We'll see if we can fix this next update, but until then you can manually fix it yourself.

Sorry about that. :/

**Comment by talonos2** [comment]
Will be fixed even in pre-existing worlds.
