### ISSUE TITLE
Out of memory - heap space / GC overhead limit exceeded

### ISSUE THREAD

**Issue by Hashimatsu** [talonos2/BlightfallTracker#109]
Cant quite think of anything for this. System specs: windows 7 x64bit - 8 gb ram  (tired allocating 2 - 3 - 3.5- 4 - 5GB of ram and got the same result(s) each time) 4.00GHz amd processor nvidia 760 graphics card (drivers up to date) Java 1.8 version 60 64bit (also tried with java 1.7 verson 67 64bit) I have reinstalled technic (and blightfall) after testing for the crash at each ram allotment and each time same errors. The  reports are as follows heap space first  if you need the gc overhead crash as well i will paste it in a reply if you need more info or want me to put this some place else let me know.

---

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/28/15 11:34 AM
Description: Updating screen events

java.lang.OutOfMemoryError: Java heap space
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1633)

-- Affected screen --
Details:
    Screen name: adubbz.lockdown.gui.GuiNonMultiplayerMainMenu
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1633)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 18972344 bytes (18 MB) / 502267904 bytes (479 MB) up to 502267904 bytes (479 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 2 loaded mod(s)
          - VoxelMap version 1.5.13
          - Mouse Tweaks version 2.4.4
    LaunchWrapper: 44 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: squeek.applecore.asm.TransformerModuleHandler
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: com.wirsbo.main.ClassTransformer
          - Transformer: net.technicpack.blightcore.coremod.BlightCoreClassTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyClassTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: net.technicpack.notimefix.coremod.NoTimeFixClassTransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: net.technicpack.blightcore.coremod.BlightCoreAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyAccessTransformer
          - Transformer: net.technicpack.notimefix.coremod.NoTimeFixAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: lumien.perfectspawn.Transformer.PSClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: ~~ERROR~~ OutOfMemoryError: Java heap space
    AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-268
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    TConstruct Environment: Environment healthy.
    NetherOres: Lacking version information.
    RedstoneArsenal: -[1.7.10]1.1.0-80
    ThermalDynamics: -[1.7.10]1.0.0RC7-98
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:ON
    Launched Version: 1.7.10-Forge10.13.2.1291
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.60, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Blightfall.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

I will attempt to find my crash report but for now here is part of the console from the second error
# 

[B#313]  [19:28:51] [Server thread/INFO]: Preparing start region for level 0
[B#313]  [19:28:52] [Server thread/INFO]: Preparing spawn area: 0%
[B#313]  [19:28:53] [Server thread/INFO]: Preparing spawn area: 12%
[B#313]  [19:28:55] [Server thread/INFO]: Preparing spawn area: 26%
[B#313]  [19:28:57] [Server thread/INFO]: Preparing spawn area: 29%
[B#313]  [19:28:58] [Server thread/INFO]: Preparing spawn area: 30%
[B#313]  [19:28:59] [Server thread/INFO]: Preparing spawn area: 35%
[B#313]  [19:29:00] [Server thread/INFO]: Preparing spawn area: 38%
[B#313]  [19:29:02] [Server thread/INFO]: Preparing spawn area: 40%
[B#313]  [19:29:03] [Server thread/INFO]: Preparing spawn area: 41%
[B#313]  [19:29:09] [Server thread/INFO]: Preparing spawn area: 41%
[B#313]  [19:29:15] [Server thread/INFO]: Preparing spawn area: 41%
[B#313]  [19:29:17] [Server thread/ERROR]: Encountered an unexpected exception
[B#313]  java.lang.OutOfMemoryError: GC overhead limit exceeded
[B#313]     at java.io.WinNTFileSystem.resolve(Unknown Source) ~[?:1.8.0_60]
[B#313]     at java.io.File.<init>(Unknown Source) ~[?:1.8.0_60]
[B#313]     at net.minecraft.world.chunk.storage.RegionFileCache.func_76550_a(SourceFile:44) ~[aqj.class:?]
[B#313]     at net.minecraft.world.chunk.storage.RegionFileCache.func_76549_c(SourceFile:84) ~[aqj.class:?]
[B#313]     at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:114) ~[aqk.class:?]
[B#313]     at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20) ~[ChunkIOProvider.class:?]
[B#313]     at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
[B#313]     at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343) ~[AsynchronousExecutor.class:?]
[B#313]     at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
[B#313]     at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
[B#313]     at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
[B#313]     at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
[B#313]     at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) ~[MinecraftServer.class:?]
[B#313]     at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) ~[bsx.class:?]
[B#313]     at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
[B#313]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#313]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#313]  Exception in thread "Server thread" [19:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: GC overhead limit exceeded
[B#313]  [19:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.IdentityHashMap.resize(Unknown Source)
[B#313]  [19:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.IdentityHashMap.put(Unknown Source)
[B#313]  [19:29:29] [Client thread/INFO]: Stopping!
[B#313]  [19:29:30] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[B#313]  [19:29:30] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[B#313]  [19:29:31] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[B#313]  [19:29:31] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[B#313]  Exception in thread "Thread-16" [19:29:35] [Thread-16/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: GC overhead limit exceeded
[B#313]  Exception in thread "Thread-1" [19:29:36] [Thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: GC overhead limit

**Comment by DaFiren** [comment]
I have the same problem! I gave up trying to fix it a while back while I was still using windows 8.1, but it happens on windows 10 as well. Really hoping someone can figure out the issue and provide a fix.

**Comment by Hashimatsu** [comment]
The only reason im even posting this is  because it is an error my girlfriend is having and the reason I thought it was strange is that we are using the "same" computer (I built us each a computer using the same parts i just put more ram in mine iv got 16 gigs shes got 8) but we have the same updates and everything else is identical but I can run blightfall no problem she only ever gets these errors. I even thought there might be some bad ram somewhere and ran a check for bad sectors and her ram is clean so im just really lost.

**Comment by SelenaQuartzRose** [comment]
"java.lang.OutOfMemoryError: GC overhead limit exceeded"
GC overhead limit reached means that Java is spending too much clock time of CPU cycles repeatedly doing garbage collection for not enough return. This can mean several things, like it is trying to clear up memory for new processes, or that there are a lot of classes being repeatedly initialized and closed out causing the garbage collector to run more often than it should.

Since it appears only 18MB of RAM was being used out of 479MB pre-allocated to the instance, it would seem that most likely this is not an issue of running out of available RAM but more likely a code-related issue.

Tell me, are you running the newest version of Blightfall? (2.1.2) If you are, could you please try using an older version (such as 2.1.0) and see if the error persists? If 2.1.0 runs but not 2.1.2, it might be related to one of the new mods added in the recent update. In particular, Cooking For Blockheads can be a little janky and was causing world-destroying crashes in version 2.1.1.

Another test you could try:
Since it seems to be crashing during world-loading, after all mods are initialized, can you try hosting to LAN on your PC and joining the multi-player using her PC?

With results from both of these tests it might be possible to narrow down the problem.
(Note: I am not a moderator or have any connection to the modpack. Just trying to be a friendly, helpful, Java-savvy programmer.)

**Comment by Hashimatsu** [comment]
Sorry it took so long to reply sibling graduations and what not anyhow tried it on the older versions and got the same errors and doing lan and server gives the same errors.

**Comment by SelenaQuartzRose** [comment]
I think I have an idea of what may be the problem, but I am not sure what is causing it.
"JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m -Xmx512M"
Your JVM flags are bizarre. First it sets the maximum RAM size to 4GB with "-Xmx4096m", but then it sets the maximum RAM for the heap to just half a GB with "-Xmx512M". I am not sure, but I think this may be a problem with the Launcher, and not explicitly Blightfall.
Can you run any other intense modpacks on her PC, like modern Tekkit? I don't understand the Technic Launcher's inner workings well enough to know exactly where this extra argument "-Xmx512M" is coming from but I know for a fact that it must be the source of your problem.

**Comment by SelenaQuartzRose** [comment]
Scratch that: I've had a talk with @CannibalVox from the Technic Launcher team and he's convinced me it's likely that your system has "environment variables" that are overriding the Technic Launcher's java arguments. @Hashimatsu this is relatively advanced stuff so I am not sure I can walk you through it, but please try the following:
1. Open the Start Menu, Right-Click on "Computer", and select "System Properties"
2. Click "Advanced System Settings". In the dialog box that opens, make sure you are on the "Advanced" tab.
3. Click on the "Environment Variables..." button. Under "System Variables", find "JAVA_ARGS" and click on it. Then click "Edit".
4. The "Variable Value" should contain the text "-Xmx512M". Remove this text, then click "OK".
5. Try running Blightfall again. If it fails, please post a new crash report.

**Comment by Hashimatsu** [comment]
Thanks Doc. That did it all is working now I hope this can help some other people too and thanks again you went way out of your way to help and also talonos thanks for not gettin rid of this even though it was the wrong place to post this issue.

**Comment by SelenaQuartzRose** [comment]
I am so, so, so very glad that your issue has been resolved @Hashimatsu and I hope that @Talonos2 is proud of me for seeing you through this so you can play Blightfall with your girlfriend. :D
