### ISSUE TITLE
Cant load singleplayer

### ISSUE THREAD

**Issue by trapmaster1254** [talonos2/BlightfallTracker#111]
Whenever i open my single player world instead of loading chunks it says shutting down internal server and boots me back to the main menu can anyone help me with this?

**Comment by SelenaQuartzRose** [comment]
It would be helpful if you left a http://www.pastebin.com copy of what was in the Technic Launcher Console at the time. (That's the black screen with white text that has all the computer-speak on it)

If I had to take a wild shot in the dark, I would guess that you do not have enough RAM allocated to load the world into memory. You need a minimum of 2GB allocated to play the modpack well. This means you should be using the 64-bit version of Java and have at least 4GB (preferably 8GB) installed on your computer.

But that is just a guess.

**Comment by talonos2** [comment]
Generally, it won't load if the memory is too small. And if it crashes due to memory constraints, it usually crashes all the way to the launcher, not to the main menu. But as Dr. D said, I cannot diagnose this without a crash report.
