### ISSUE TITLE
[Fixed] Crash Thermal Dynamics Fluiduct

### ISSUE THREAD

**Issue by JokarLP** [talonos2/BlightfallTracker#114]
I have see there is a Issues with a filter from this mod but i also thought this crash log and server log are interesting to you. It happens after placing any Fluiduct. The Server Crashes everytime if I would join.

Crash Log: http://pastebin.com/AeyS7NzG
Server Log: http://pastebin.com/0ufEG613 (Crash Log as title should here be called Server Log)

Is there a connection with the Ender Tank NEI Crash? So Could it be the Forge Version and not the Thermal Dynamics Mod?
Fast help would be nice. I have whitelisted the Server till it is fixed

**Comment by JokarLP** [comment]
Fixed! It was the Cauldron version. The Forge in the Cauldron version wasn't the same how the Forge Version from the ModPack

**Comment by JokarLP** [comment]
So. Closed!

**Comment by talonos2** [comment]
Wonderful. I mentioned it was likely the forge version!

This should fix the endertank issue as well.

I'm so glad it worked out!

**Comment by JokarLP** [comment]
Yeah. The Ender Tank NEI Crash is also fixed now :)
