### ISSUE TITLE
sugarcane not growing in bio dome or at all

### ISSUE THREAD

**Issue by DarkWolf204** [talonos2/BlightfallTracker#117]
hey I downloaded Blightfall and everything works but some quests reqire books wich you need paper and intern need sugarcane so I found some but when I planted it next to water on sand and dirt it never grew even after an hour anyone know a fix or if this was intended ?

**Comment by talonos2** [comment]
Dunno what to tell you. It's growing find in epsilon, and that's a desert.

**Comment by DarkWolf204** [comment]
ok I got another one in the blightfall modpack I'm getting weird vamprisim like effects is there vamprism in that modpack?

**Comment by DarkWolf204** [comment]
how dose a LAN player reset blightfall?

**Comment by SelenaQuartzRose** [comment]
Sugar cane grows for me just fine.
What do you mean, "Vampirism like effects"? Do you mean your character is getting effects like Weakness, Slowness, and Mining Fatigue? This happens if you're low on health or hunger.

"how dose a LAN player reset blightfall?"
I don't even know how to answer this. What are you trying to ask?

**Comment by talonos2** [comment]
In all honesty, I think I'm going to have to close this thread. It's for bug reports, not general help. "Sugarcane is not growing" is a bug that I'm glad you would report, just in case other people are having the same issue. "Is vampirism in the modpack" is a question, as is "How does a LAN player reset Blightfall." These would be better suited for the discussion page, the Technic forums, or the IRC channel. 

http://forums.technicpack.net/forum/82-blightfall-discussion/
