### ISSUE TITLE
Typos and Errors in "Mining and Resource Collection"

### ISSUE THREAD

**Issue by SelenaQuartzRose** [talonos2/BlightfallTracker#118]
Just two quick errors I found in this book - 
1. The entry on Lemurite says "Allows with Shadow Iron", should say "Alloys".
2. The entry on Ceruclase displays the inventory picture for Vyroxeres Ore instead of Ceruclase Ore.

P.S. I'm wondering if Caves to Kingdoms has any commands or shortcuts to unlock book information on all materials? I checked all five of the books on Materials, Tools, and Armor and didn't find any other errors or typos, but I have less than half of each unlocked.

**Comment by SniperXPrime** [comment]
Nether ruby ore missing in the book?
(Required for constructing a blood alter for the blood magic mod)

**Comment by SelenaQuartzRose** [comment]
Additional Typo: In the quest book, there is a quest named "Discover Ignatus!" (under the Geologist, nether ores quests). Both the quest name and the quests's descriptive text are spelled incorrectly - The ore is called "Ignatius".

**Comment by talonos2** [comment]
The command is /oreDiscoveryAll.

Those errors are fixed.

Thanks a ton for all the help!
