### ISSUE TITLE
Duplication Bug - BetterStorage Storage Crate + Blockheads Cooking Table

### ISSUE THREAD

**Issue by everseeking** [talonos2/BlightfallTracker#119]
BetterStorage Storage Crate & Cooking for Blockheads Cooking Table
- Tested making foods both with and without Pam's cooking utensils (still duplicates)
- Ingredients must have quantity > 1 in the crate
  ![untitled-1](https://cloud.githubusercontent.com/assets/798527/9650532/5e24ef78-51d2-11e5-96d0-95d8060a0554.jpg)
  ![untitled-2](https://cloud.githubusercontent.com/assets/798527/9650533/5e28709e-51d2-11e5-9a9c-3bc16113688b.jpg)

**Comment by talonos2** [comment]
Solved by upgrading C4B.
