### ISSUE TITLE
Can not launch Blightfall

### ISSUE THREAD

**Issue by ghost** [talonos2/BlightfallTracker#12]
Hi i have discovered a glitch/bug where you cant play blightfall which happens when you launch it gos straight back to your technic launcher. No errors are shown and i have java 8 and 6 gigs alocated to my minecraft and i run windows 10 also but as far as im aware windows 10 does not mess with minecraft modpacks.

**Comment by talonos2** [comment]
Could you turn the console on in the options menu and then send me the output of the console? If there was an error, that's where it would be.

**Comment by ghost** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 13/08/15 23:03
Description: Initializing game

java.lang.NoClassDefFoundError: scala/collection/Seq
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.getNewInstance(ILanguageAdapter.java:20)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 35 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at lumien.perfectspawn.Transformer.PSClassTransformer.transform(PSClassTransformer.java:43)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 37 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.getNewInstance(ILanguageAdapter.java:20)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 685014896 bytes (653 MB) / 1046478848 bytes (998 MB) up to 5726797824 bytes (5461 MB)
    Mod Pack: ~~ERROR~~ NullPointerException: null
    LiteLoader Mods: ~~ERROR~~ NullPointerException: null
    LaunchWrapper: 42 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: squeek.applecore.asm.TransformerModuleHandler
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: net.technicpack.blightcore.coremod.BlightCoreClassTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyClassTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: net.technicpack.notimefix.coremod.NoTimeFixClassTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: net.technicpack.blightcore.coremod.BlightCoreAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyAccessTransformer
          - Transformer: net.technicpack.notimefix.coremod.NoTimeFixAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: lumien.perfectspawn.Transformer.PSClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 110 mods loaded, 110 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.85.1291} [Forge Mod Loader](modpack.jar) Unloaded->Constructed
    Forge{10.13.2.1291} [Minecraft Forge](modpack.jar) Unloaded->Constructed
    appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed
    blightcore{1.2.0} [Blight Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed
    newradicalbotany{1.1.2} [New Radical Botany](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed
    notimefix{2.1.0} [No Time Fix](minecraft.jar) Unloaded->Constructed
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed
    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed
    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed
    appliedenergistics2{rv2-stable-1} [Applied Energistics 2](appliedenergistics2-rv2-stable-1.jar) Unloaded->Constructed
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed
    ArmorStatusHUD{1.28} [ArmorStatusHUD](ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-268.jar) Unloaded->Constructed
    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed
    Automagy{0.24.1} [Automagy](Automagy-1.7.10-0.24.1.jar) Unloaded->Constructed
    betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed
    BiblioCraft{1.10.3} [BiblioCraft](BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed
    Mantle{1.7.10-0.3.2.jenkins186} [Mantle](Mantle-1.7.10-0.3.2.jenkins186.jar) Unloaded->Constructed
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded->Constructed
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed
    BigReactors{0.4.1A2} [Big Reactors](BigReactors-0.4.1A2.jar) Unloaded->Constructed
    AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed
    Botania{r1.6-191} [Botania](Botania r1.6-191.jar) Unloaded->Constructed
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed
    customnpcs{1.7.10c} [CustomNpcs](CustomNPCs_1.7.10c.jar) Unloaded->Constructed
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed
    ForgeMultipart{1.1.1.321} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed
    ExtraUtilities{1.2.5} [Extra Utilities](extrautilities-1.2.5.jar) Unloaded->Constructed
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed
    TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} [Tinkers' Construct](TConstruct-1.7.10-1.8.3-RFNerf.jar) Unloaded->Constructed
    Metallurgy{4.0.5} [Metallurgy 4](Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed
    harvestcraft{1.7.10g} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed
    ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-471.jar) Unloaded->Constructed
    ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed
    HardcoreQuesting{The Journey (4.2.3)} [Hardcore Questing Mode](HQM-The Journey %284.2.3%29.jar) Unloaded->Constructed
    ImLookingAtBlood{1.1} [I'm Looking At Blood](ImLookingAtBlood-1.7.2-1.1a.jar) Unloaded->Constructed
    inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) Unloaded->Constructed
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](inventorytweaks-1.58-147.jar) Unloaded->Constructed
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed
    Lockdown{2.0.0} [Lockdown](Lockdown-2.0.0.0.jar) Unloaded->Constructed
    LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed
    modelcitizens{1.0.1} [Model Citizens](ModelCitizens-mc1.7.10-1.0.1.jar) Unloaded->Constructed
    modtweaker2{0.7} [Mod Tweaker 2](ModTweaker 2-0.7.5.jar) Unloaded->Constructed
    MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed
    NEIPlugins{1.1.0.10-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.10-unofficial.jar) Unloaded->Constructed
    Netherless{0.9.0} [Netherless](Netherless-0.9.0.jar) Unloaded->Constructed
    NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed
    PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) Unloaded->Constructed
    RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed
    biomescanner{0.1.0} [Biome Scanner](reqcredit-v1.2.4.jar) Unloaded->Constructed
    blightbuster{0.1.0} [BlightBuster](reqcredit-v1.2.4.jar) Unloaded->Constructed
    cavestokingdoms{0.0.1} [Caves to Kingdoms](reqcredit-v1.2.4.jar) Unloaded->Constructed
    RPGAdvMod{1.0.0} [RPGAdvMod](RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed
    Schematica{1.7.5.git} [Schematica](Schematica-1.7.10-1.7.5-GenHack2.jar) Unloaded->Constructed
    SpiceOfLife{1.2.3} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded->Constructed
    StorageDrawers{1.7.10-1.5.3} [Storage Drawers](StorageDrawers-1.7.10-1.5.3.jar) Unloaded->Constructed
    TabulaRasa{1.7.10R1.0.1} [Tabula Rasa](TabulaRasa-[1.7.10]1.0.1-3-Blight3.jar) Unloaded->Constructed
    playerzombiemod{v1} [Tainted Players](TaintedPlayers-v1-1.7.10.jar) Unloaded->Constructed
    tcnodetracker{1.1.0} [TC Node Tracker](tcnodetracker-1.7.10-1.1.0.jar) Unloaded->Constructed
    TerrainControl{2.7.0-SNAPSHOT} [Terrain Control](terraincontrol-forge-2.7.0-colored-lockhack.jar) Unloaded->Constructed
    thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed
    thaumicenergistics{0.8.10.6} [Thaumic Energistics](thaumicenergistics-0.8.10.6.jar) Unloaded->Constructed
    ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0RC7-98.jar) Unloaded->Constructed
    TiCTooltips{1.2.4} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed
    TML{3.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-3.0.1.B22-universal.jar) Unloaded->Constructed
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded->Constructed
    UndergroundBiomes{0.7} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-test41.jar) Unloaded->Constructed
    ubcores{1.7.10-0.1.2.0} [UBC Ore Registrar](UBCOres-1.7.10-0.1.2.0.jar) Unloaded->Constructed
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed
    McMultipart{1.1.1.321} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed
    HungerOverhaul{1.7.10-1.0.0.DEV.c9b8cee} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0-ConfigHack-2.jar) Unloaded->Constructed
    IguanaTweaksTConstruct{1.7.10-2.1.4.DEV.0edeedd} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.4.DEV.0edeedd.jar) Unloaded->Constructed
    ForgeMicroblock{1.1.1.321} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded
    AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-268
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    TConstruct Environment: Environment healthy.
    NetherOres: Lacking version information.
    RedstoneArsenal: -[1.7.10]1.1.0-80
    ThermalDynamics: -[1.7.10]1.0.0RC7-98
    Launched Version: 1.7.10-Forge10.13.2.1291
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.62, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Blightfall.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by ghost** [comment]
I could not upload a txt file so this is all i could do.

**Comment by talonos2** [comment]
Looks like you're missing a library. You should be downloading those automatically when you run Blightfall; I think it's something on the launcher's end. I'll ask one of the launcher guys to take a look at it.

**Comment by ghost** [comment]
Odd i dont have issues with other modpacks

**Comment by talonos2** [comment]
The launcher engineer recommends you delete and reinstall the pack and see if that helps. I'm sorry, we're really not sure what to make of this one yet.
