### ISSUE TITLE
HQM consumes wrong energy cell

### ISSUE THREAD

**Issue by caysyka** [talonos2/BlightfallTracker#120]
I tried to refill my leadstone energy cell to unlock the higher tier refill quests (Why are they sequential anyway?) and instead of consuming my empty leadstone energy cell it consumed my resonant energy cell. I assume this is simply a limitation of HQM, but I thought you should know.

**Comment by talonos2** [comment]
Oh hey. I _can_ fix it. That's cool. Thanks HQM. </not sarcasm>
