### ISSUE TITLE
Blightfall not opening.

### ISSUE THREAD

**Issue by umiiy** [talonos2/BlightfallTracker#121]
When i try to open Blightfall, doesn't open, once i click the play button it looks like its loading up (it didn't open Minecraft it just had loading bars at the bottom of the technic launcher doing stuff) but after it finished it didn't open the game just went back to the technic launcher. I've tried both the recommended and latest version of the pack but neither worked. I have also reinstalled the game a few times, which as far as i can tell hasn't changed anything. I can play on other technic mod packs, so i don't know why this isn't working.

**Comment by laith12301** [comment]
i have the same proplem

**Comment by SelenaQuartzRose** [comment]
Try posting a crash log if you want any help. No one can find the source of the problem without that.

They will be in [technic directory]\modpacks\blightfall\crash-reports

If you can't find the directory, then from the Launcher, select Blightfall and click "Modpack Options" at the top-right. Then next to "Install Directory", click "Open". It should open the blightfall folder, with the "crash-reports" folder inside of it...

**Comment by talonos2** [comment]
Closed until logs are provided.
