### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by laith12301** [talonos2/BlightfallTracker#122]
when i start the game it be black screen for while then the loading screen appear and after it finish the game crash

**Comment by laith12301** [comment]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 9/7/15 4:26 PM
Description: Registering texture

java.lang.OutOfMemoryError: Registering texture
    at java.util.zip.Inflater.inflateBytes(Native Method)
    at java.util.zip.Inflater.inflate(Unknown Source)
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at javax.imageio.stream.MemoryCache.loadFromStream(Unknown Source)
    at javax.imageio.stream.MemoryCacheImageInputStream.read(Unknown Source)
    at javax.imageio.stream.ImageInputStreamImpl.readByte(Unknown Source)
    at com.sun.imageio.plugins.wbmp.WBMPImageReaderSpi.canDecodeInput(Unknown Source)
    at javax.imageio.ImageIO$CanDecodeInputFilter.filter(Unknown Source)
    at javax.imageio.spi.FilterIterator.advance(Unknown Source)
    at javax.imageio.spi.FilterIterator.<init>(Unknown Source)
    at javax.imageio.spi.ServiceRegistry.getServiceProviders(Unknown Source)
    at javax.imageio.ImageIO.getImageReaders(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:127)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61)
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.zip.Inflater.inflateBytes(Native Method)
    at java.util.zip.Inflater.inflate(Unknown Source)
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at javax.imageio.stream.MemoryCache.loadFromStream(Unknown Source)
    at javax.imageio.stream.MemoryCacheImageInputStream.read(Unknown Source)
    at javax.imageio.stream.ImageInputStreamImpl.readByte(Unknown Source)
    at com.sun.imageio.plugins.wbmp.WBMPImageReaderSpi.canDecodeInput(Unknown Source)
    at javax.imageio.ImageIO$CanDecodeInputFilter.filter(Unknown Source)
    at javax.imageio.spi.FilterIterator.advance(Unknown Source)
    at javax.imageio.spi.FilterIterator.<init>(Unknown Source)
    at javax.imageio.spi.ServiceRegistry.getServiceProviders(Unknown Source)
    at javax.imageio.ImageIO.getImageReaders(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:127)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)

-- Resource location being registered --
Details:
    Resource location: minecraft:textures/atlas/items.png
    Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61)
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 89707776 bytes (85 MB) / 474902528 bytes (452 MB) up to 1037959168 bytes (989 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 2 loaded mod(s)
          - VoxelMap version 1.5.13
          - Mouse Tweaks version 2.4.4
    LaunchWrapper: 44 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: squeek.applecore.asm.TransformerModuleHandler
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: com.wirsbo.main.ClassTransformer
          - Transformer: net.technicpack.blightcore.coremod.BlightCoreClassTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyClassTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: net.technicpack.notimefix.coremod.NoTimeFixClassTransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: net.technicpack.blightcore.coremod.BlightCoreAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyAccessTransformer
          - Transformer: net.technicpack.notimefix.coremod.NoTimeFixAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: lumien.perfectspawn.Transformer.PSClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 116 mods loaded, 116 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1291} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1291} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    blightcore{1.2.0} [Blight Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    newradicalbotany{1.1.2} [New Radical Botany](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized
    notimefix{2.1.0} [No Time Fix](minecraft.jar) Unloaded->Constructed->Pre-initialized
    PlayerAPI{1.4} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized
    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv2-stable-1} [Applied Energistics 2](appliedenergistics2-rv2-stable-1.jar) Unloaded->Constructed->Pre-initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
    ArmorStatusHUD{1.28} [ArmorStatusHUD](ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-268.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Automagy{0.24.1} [Automagy](Automagy-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized
    betterrain{0.15} [Better Rain](betterrain-1.7.2-1.7.10_0.15.jar) Unloaded->Constructed->Pre-initialized
    betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.10.3} [BiblioCraft](BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins186} [Mantle](Mantle-1.7.10-0.3.2.jenkins186.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.1A2} [Big Reactors](BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed->Pre-initialized
    Botania{r1.6-191} [Botania](Botania r1.6-191.jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    cookingbook{1.0.0} [Cooking for Blockheads](cookingbook-mc1.7.10-1.0.54-mt3hack.jar) Unloaded->Constructed->Pre-initialized
    customnpcs{1.7.10c} [CustomNpcs](CustomNPCs-1.7.10c-herohack2.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.1.321} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.2.5} [Extra Utilities](extrautilities-1.2.5.jar) Unloaded->Constructed->Pre-initialized
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} [Tinkers' Construct](TConstruct-1.7.10-1.8.3-RFNerf.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy{4.0.5} [Metallurgy 4](Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.10g} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized
    ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-471.jar) Unloaded->Constructed->Pre-initialized
    ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized
    HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) Unloaded->Constructed->Pre-initialized
    HardcoreQuesting{The Journey (4.2.3)} [Hardcore Questing Mode](HQM-The Journey %284.2.3%29.jar) Unloaded->Constructed->Pre-initialized
    ImLookingAtBlood{1.1} [I'm Looking At Blood](ImLookingAtBlood-1.7.2-1.1a.jar) Unloaded->Constructed->Pre-initialized
    inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](inventorytweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Lockdown{2.0.0} [Lockdown](Lockdown-2.0.0.0.jar) Unloaded->Constructed->Pre-initialized
    LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized
    modelcitizens{1.0.1} [Model Citizens](ModelCitizens-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized
    modtweaker2{0.7} [Mod Tweaker 2](ModTweaker 2-0.7.5.jar) Unloaded->Constructed->Pre-initialized
    MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.10-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.10-unofficial.jar) Unloaded->Constructed->Pre-initialized
    Netherless{0.9.0} [Netherless](Netherless-0.9.0.jar) Unloaded->Constructed->Pre-initialized
    NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized
    PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized
    purplepanic{1.0.1} [Purple Panic](purplepanic-1.0.1.jar) Unloaded->Constructed->Pre-initialized
    RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized
    biomescanner{0.1.0} [Biome Scanner](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized
    blightbuster{0.1.0} [BlightBuster](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized
    cavestokingdoms{0.0.1} [Caves to Kingdoms](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized
    RPGAdvMod{1.0.0} [RPGAdvMod](RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Schematica{1.7.5.git} [Schematica](Schematica-1.7.10-1.7.5-GenHack2.jar) Unloaded->Constructed->Pre-initialized
    SpiceOfLife{1.2.4} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
    StorageDrawers{1.7.10-1.5.3} [Storage Drawers](StorageDrawers-1.7.10-1.5.3.jar) Unloaded->Constructed->Pre-initialized
    TabulaRasa{1.7.10R1.0.1} [Tabula Rasa](TabulaRasa-[1.7.10]1.0.1-3-Blight3.jar) Unloaded->Constructed->Pre-initialized
    playerzombiemod{v1} [Tainted Players](TaintedPlayers-v1-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    tcnodetracker{1.1.0} [TC Node Tracker](tcnodetracker-1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    TerrainControl{2.7.0-SNAPSHOT} [Terrain Control](terraincontrol-forge-2.7.0-colored-lockhack.jar) Unloaded->Constructed->Pre-initialized
    thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized
    thaumicenergistics{0.8.10.6} [Thaumic Energistics](thaumicenergistics-0.8.10.6.jar) Unloaded->Constructed->Pre-initialized
    ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0RC7-98.jar) Unloaded->Constructed->Pre-initialized
    TiCTooltips{1.2.4} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized
    TML{3.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-3.0.1.B22-universal.jar) Unloaded->Constructed->Pre-initialized
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded->Constructed->Pre-initialized
    UndergroundBiomes{0.7} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-test41.jar) Unloaded->Constructed->Pre-initialized
    ubcores{1.7.10-0.1.2.0} [UBC Ore Registrar](UBCOres-1.7.10-0.1.2.0.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.1.321} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized
    HungerOverhaul{1.7.10-1.0.0.DEV.c9b8cee} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0-ConfigHack-2.jar) Unloaded->Constructed->Pre-initialized
    IguanaTweaksTConstruct{1.7.10-2.1.4.DEV.0edeedd} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.4.DEV.0edeedd.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.1.321} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-268
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    TConstruct Environment: Environment healthy.
    NetherOres: Lacking version information.
    RedstoneArsenal: -[1.7.10]1.1.0-80
    ThermalDynamics: -[1.7.10]1.0.0RC7-98
    Launched Version: 1.7.10-Forge10.13.2.1291
    LWJGL: 2.9.1
    OpenGL: GeForce 8600 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Blightfall.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by SelenaQuartzRose** [comment]
It looks to me like you don't have enough memory to run the modpack. You seem to be using a 32-bit operating system, so I doubt you will be able to. This modpack takes quite a bit of memory and works best with 64-bit systems that are able to dedicate at least 2GB of RAM to Blightfall.
Try assigning the modpack to use 1.5GB of RAM (this is the max Java can use on 32-bit mode). If it still won't work, I'm pretty sure your computer just can't handle it. 

Try asking on the Technic Forums if you need further help, I am pretty sure this is a computer hardware problem and not a bug with the modpack.

Disclaimer: Not a representative of the mod-pack. Just a helpful person.

**Comment by laith12301** [comment]
I have 2GB ram why it give me just 1GB?

**Comment by SelenaQuartzRose** [comment]
Some RAM is taken up by your operating system, and Java is only allowed to use so much of it. Also, the amount of RAM Java can use is even lower when you are using a 32-bit operating system.

I'm sorry to say but I am pretty sure your computer is not good enough to run Blightfall. Even if you upgraded your RAM to 4GB there's a good chance you would not be able to load the modpack.

Wish I had more advice for you but this is definitely not a bug with Blightfall - it's your PC. You will probably need to use a newer computer if you want to run Blightfall. Anything with a 64-bit operating system and at least 4GB of system RAM should work.

**Comment by talonos2** [comment]
I believe Dr. D is right on the mark here.
