### ISSUE TITLE
Is this how the Tainted Alchemist is supposed to look?

### ISSUE THREAD

**Issue by SelenaQuartzRose** [talonos2/BlightfallTracker#126]
Somehow I get the feeling that steve_tainted.png is not quite 100% compatible with the Thaumcraft.TaintedVillager model.

![alchemist](https://cloud.githubusercontent.com/assets/10502748/9792109/7c70a76c-57ac-11e5-99c3-c12e5623a7db.png)

I hope you get a laugh out of this, because I'm not quite sure how you'd be able to propagate a fix to this onto existing worlds o_O (World was created with version 2.1.0, so I apologize if this has been fixed already...)

**Comment by talonos2** [comment]
It's possible with the "HeroHack" technology Canvox used to make it so the
tainted hero doesn't respawn infinitely.

It's uh... ugly, but not mechanically problematic, so it's been a lower
priority fix, but we _are_ planning on fixing it.

**Comment by SelenaQuartzRose** [comment]
Glad to hear a fix is in the works and I'm not surprised it's a "lower priority fix" - it doesn't change gameplay. As you said, it's just ugly.
Just doing my duty to report issues. Blightfall is by far the best modpack/map I've ever played and I feel inclined to offer feedback and help to make it the best it can be. Keep up the great work.

**Comment by talonos2** [comment]
Your feedback is appreciated. (Especially considering your high quality bug
reports.)

**Comment by talonos2** [comment]
![2015-09-13_08 17 00](https://cloud.githubusercontent.com/assets/3359830/9838244/e1be318c-5a15-11e5-8720-d806e21163f6.png)
