### ISSUE TITLE
Extremely high CPU usage and unplayably slow after 2.1.4 update

### ISSUE THREAD

**Issue by rscarson** [talonos2/BlightfallTracker#132]
Tried rolling back to 2.1.3, did not fix it. Game was very smooth until today's update

**Comment by rscarson** [comment]
Update: 2.1.1a rollback also did not fix it. I must conclude that 2.1.4 modified either the map, or some configuration.

**Comment by rscarson** [comment]
New map has the same problem

**Comment by SelenaQuartzRose** [comment]
I haven't had any issues. If a new map has the same problem and rolling back to the previous version has the same problem, I can only suggest making a new map in the previous version. If it is still extremely laggy then something has changed with your PC or your Java installation, and there's no rational way it could be a Blightfall problem. Please try this and let me know.

**Comment by talonos2** [comment]
I hear this might be a problem with a new java version. Did you update java recently, perchance?
