### ISSUE TITLE
Scouts quests locked themselves, colonist quests reset. 

### ISSUE THREAD

**Issue by bfgmetalhead** [talonos2/BlightfallTracker#144]
This is on a multiplayer server, I noticed today that the scouts quests are now locked and greyed out like the Dark one was. Also it seems that I can not interact with the scanner on the jaded. 

Please help I want to continue this mod's pretty cool narrative.

**Comment by talonos2** [comment]
You must have joined a party with a member of another biodome. Look at #129
for info on how to fix it.
