### ISSUE TITLE
re: Scout missions gone

### ISSUE THREAD

**Issue by bfgmetalhead** [talonos2/BlightfallTracker#148]
Hay, thanks for your previous reply. We tried your advice of deleting the .dat files from the world save of the offending players. The quests remain missing. 

Anything else you can offer? We kinda are out of idea's at our end.

**Comment by talonos2** [comment]
Wrong .dat file. You have to delete "Players.dat" from the
"HardcoreQuesting" folder of the world save.

If you still have the players' .dat files from the "playerdata" folder in a
recycle bin or something, you can restore them. No questing data is stored
in that file.

**Comment by bfgmetalhead** [comment]
Ah, that was our issue, thx for your help man. We'll get back to the awsoem modpack now ^_^
