### ISSUE TITLE
Blightfall server not working 

### ISSUE THREAD

**Issue by sheawild** [talonos2/BlightfallTracker#149]
gives me Java.net.connectExeption: connectionrefused
allways gives me this error when i try to log into my server 
it also also unloads at the end for some resen its correctly port forewarded, (im 100% shure)
Unloding dimensienn 1

**Comment by talonos2** [comment]
No logs and the scope of this bug can be too large. The server has been tested working in other settings, and this seems more like a network error than a modpack bug. I'm going to close this.
