### ISSUE TITLE
Mining and Resource book resetting in SMP

### ISSUE THREAD

**Issue by Blaquetooth** [talonos2/BlightfallTracker#15]
I am neither the server admin or party leader. The entries for the ores reset each time I log into the server. A minor annoyance, and could be a permissions thing. I don't know, but there it is.

(edit: actually, I don't have to relog into the server. I have gotten several notices for gravel alone this session.)

**Comment by talonos2** [comment]
Fixed by https://github.com/CannibalVox/CavesToKingdoms/releases/tag/1.2.6
