### ISSUE TITLE
Totem of Dawn stops working after chunk is unloaded the loaded

### ISSUE THREAD

**Issue by omglolbah** [talonos2/BlightfallTracker#18]
Placing a 'totem of dawn' block down and then leaving the area will of course stop the clean-up process. Returning to the location does NOT however resume the clean-up activity of the totem.
Breaking and placing the totem again fixes the issue.

Tested in a single-player world created with release version.

**Comment by talonos2** [comment]
Weird. Dawn totems did not act like this three weeks ago when I was testing.

We'll look into it.

**Comment by talonos2** [comment]
Fixed by https://github.com/CannibalVox/CavesToKingdoms/releases/tag/1.2.7
