### ISSUE TITLE
Screen Resolution on startup

### ISSUE THREAD

**Issue by EpicTrollFace00** [talonos2/BlightfallTracker#19]
I don't have a clue how to fix this but whenever I startup Blightfall. Once it loads up and I'm at the main menu I can't see the text becuase the actual menu screen is small in the bottom left part of the window and the rest of the window is black but if I click around it still makes the sound like I'm clicking the "Multiplayer" or "Singleplayer" tabs.

**Comment by EpicTrollFace00** [comment]
I checked the console. Apparently it's an GL error?

**Comment by talonos2** [comment]
Yep. It's an issue with certain graphics cards/drivers. I don't know what to tell you, I'm afraid.

**Comment by bochen415** [comment]
-Dforge.forceNoStencil=true

edit: since user java args are not parsed to the game that needs to be done in versions.json

**Comment by talonos2** [comment]
Perfect. Glad there's something out there. If I am not mistaken, adding to the version.json on my end will propagate it to everybody's computers, which worries me. Will this command like option adversely affect normal users in any way? (I assume stencils are there for a reason)

**Comment by bochen415** [comment]
Yeah, this setting is intended _only_ for users with crappy gpus, like intel 45 series.

**Comment by EpicTrollFace00** [comment]
Thank you both so much. And yeah I'm running a Intel Laptop from about 3 or so years ago.

**Comment by ghost** [comment]
Im having this same promblem and im just wondering, what do I need to change in the version.json file to fix it?

**Comment by bochen415** [comment]
@EpicTrollFace00 @HackerA13 New Technic Launcher build 316 has now a video settings tab in the options. You will find a "Stencil Buffer" setting there. Experiment with it until Blightfall launches.
