### ISSUE TITLE
Glitched Death

### ISSUE THREAD

**Issue by jeo6152** [talonos2/BlightfallTracker#192]
Hello,

I was sailing away from the swamp island towards the larger swamp landmass when I noticed a chunk that hadn't loaded yet.  I thought it would so I kept sailing through the space thinking it would load as usual.  However, it didn't and soon I was floating down on my boat through the ground and I could see all the underground passages and stuff.  It was pretty cool!  Reminded me of the river Styx and Charon.  It wasn't so cool after I started suffocating after about 10 seconds, then died.  I lost a lot of inventory and a precious life.  Can I get that life back?  I don't want my world to be deleted after three deaths.

Thanks

**Comment by talonos2** [comment]
You have infinite lives, and you don't drop your inventory on death as of
Blightfall 2.1. You should use the newer versions of Blightfall, they are
much, much better.

If you refuse to, there is a quest under the supplier that gives you extra
lives for a cost of 10 reputation each. I'd just go and buy like half a
dozen so you don' have to worry about forgetting and accidentally getting
your world deleted.

**Comment by talonos2** [comment]
As for the chunk load error, that's a vanilla minecraft bug I cannot do anything about. Logging out and back in fixes them.

**Comment by jeo6152** [comment]
That's weird then. I'm on version 2.1.5.

Maybe it didn't update correctly? I updated from a version I was playing around March.

On January 9, 2016, at 5:02 PM, talonos2 notifications@github.com wrote:

Closed #192.

**Comment by talonos2** [comment]
Ah, I see.

Worlds created in versions previous to 2.1.0 are somewhat broken now. Feel free to op yourself infinite hardcore lives and turn /gamerule keepInventory true, as all new worlds have alternate loss conditions and have keepInventory true by default. Nowadays, every time you die you immediately lose 10 reputation, and if you get below -150 reputation, you lose.

**Comment by jeo6152** [comment]
Great, thanks so much for your help!

Another funny thing.  I was watching a lets play of this mod pack on youtube and a funny thing I noticed is that in one of the cities in the sky, you fight the tainted hero.  I fought the sniper in the room accompanying him, but not the tainted hero himself.  That's strange, is it because of the broken map you mentioned?  If so, would it be worth it to restart the game and reset to a new non-broken world?  I'm not sure what else I would miss since I missed a big boss fight. 

```
On Saturday, January 9, 2016 9:00 PM, talonos2 <notifications@github.com> wrote:
```

 Ah, I see.Worlds created in versions previous to 2.1.0 are somewhat broken now. Feel free to op yourself infinite hardcore lives and turn /gamerule keepInventory true, as all new worlds have alternate loss conditions and have keepInventory true by default. Nowadays, every time you die you immediately lose 10 reputation, and if you get below -150 reputation, you lose.—
