### ISSUE TITLE
new server crashe while starting

### ISSUE THREAD

**Issue by mattaieus** [talonos2/BlightfallTracker#195]
It's my first time making a blightfall server so maybe i'm missing a step. When i launch my start.bat it just load a bunch of thing and at the end it decide to stop because of error. Do i need to edit something in the start.bat or anywhere else? here the crash report
[crash-2016-01-17_11.09.36-server.txt](https://github.com/talonos2/BlightfallTracker/files/93501/crash-2016-01-17_11.09.36-server.txt)

**Comment by talonos2** [comment]
This seems like a form of world corruption. Not sure where it would have come from given that other people are downloading the server just fine. I'd redownload the server and try again.

If it happens again after redownloading, please send me the _first_ crash report you get.

**Comment by mattaieus** [comment]
i deleted everything, download again and now it work.
