### ISSUE TITLE
Missing Chunks

### ISSUE THREAD

**Issue by BlueBloodMoon** [talonos2/BlightfallTracker#200]
When I play the game suddenly when i walk around there are ''black holes'' in a big area that are missing. I always have to go back to title screen and back into the world but it happening so many times. Probably 5 - 10 times a day when I play. It's all the way down including bedrock.

**Comment by talonos2** [comment]
Are you playing single-player or on a server?

Are you using airships?

**Comment by BlueBloodMoon** [comment]
On a single player and no

**Comment by Benedictum** [comment]
Try hitting shift+f3 when near one of those "black holes" a few times. It sounds like the chunk is just failing to render. 

does it look like this http://i1123.photobucket.com/albums/l549/onezumiyoukai/2014-06-10_120834.png

if so its a known issue with minecraft rendering unfortunately.

**Comment by BlueBloodMoon** [comment]
Gonna see if that works and it's missing chunks
