### ISSUE TITLE
Add Cooking for Blockheads & Super Crafting Frames

### ISSUE THREAD

**Issue by AKA-Syenite** [talonos2/BlightfallTracker#22]
Links:
http://www.curse.com/mc-mods/minecraft/231484-cooking-for-blockheads
http://www.curse.com/mc-mods/minecraft/super-crafting-frame

**Comment by talonos2** [comment]
Cooking for blockheads is probably a no. It is literally crashing any time I try and do anything with it. I think it might be either because I am using highly non-standard food mods, or because I have edited many recipes with minetweaker. Gonna look into super crafting frame later.

**Comment by AKA-Syenite** [comment]
Odd, I literally just dropped it into a fresh blightfall install, no configuration, and it worked perfectly. Do you have a crash log?
