### ISSUE TITLE
Ram box problem

### ISSUE THREAD

**Issue by KatieImagine** [talonos2/BlightfallTracker#23]
When I get the ram box up, because i don't have enough Ram. I can't click "click here to fix this problem" it says i can but i cannot. Until then i cannot play the new modpack

**Comment by talonos2** [comment]
Quick question: Do you have a 32 bit operating system?

**Comment by SuperHappyME** [comment]
Mine is a 64-bit system, I have the newest version of java, but it still refuses to work. What can I do then?

**Comment by KatieImagine** [comment]
I do have a 32 bit

**Comment by talonos2** [comment]
You require a 64 bit system to play Blightfall, I am afraid. :(
