### ISSUE TITLE
Can't play on my world.

### ISSUE THREAD

**Issue by Lairfite** [talonos2/BlightfallTracker#233]
This is really annoying, one day I can play the other I can't the world loads until I can see I'm in jaded then the whole thing crashes, the other 2 worlds I got loads like normal and if totally fine but the one I actually use doesn't... 
I saw others having the same kind of problem and that I need the crash report, but I don't know if there is any specific part that is needed so I just copied it all.

[crash-2017-04-06_07.39.37-client.txt](https://github.com/talonos2/BlightfallTracker/files/901631/crash-2017-04-06_07.39.37-client.txt)

**Comment by talonos2** [comment]
Thanks for the crash report: This would have been completely unsolvable without it.

Try the following:

Go into the config folder. Locate the file "Forge.cfg" there is a line for removing erroring tile entities. turn this from false to true. Restart the world and load the chunks the crash is happening at. Afterwards turn the config back to false. The issue should be fully resolved then.

**Comment by Lairfite** [comment]
Thank you so much!
