### ISSUE TITLE
Discovery of Astral Silver notification broken.

### ISSUE THREAD

**Issue by zhukant** [talonos2/BlightfallTracker#38]
Upon first mining a block of "Astral Silver" ore, the notification uses the technical term for the mineral rather than the player-friendly term. 

Steps to reproduce:
Obtain the materials books from the quest line.
Mine a block of Astral Silver ore. 
-> In my case, I used a 100% Oureclase pickaxe with 9 pieces of redstone on it, and the Astral Silver was inside Andesite rock
Receive a notification about new materials being unlocked in your materials book.

Expected result: 
The notification should read "Your discovery of astral silver has unlocked more info in your materials books!"

Actual result: 
The notification reads, "Your discovery of discover.cavestokingdoms.astralsilver has unlocked more info in your materials books!"
![2015-08-16_20 20 39](https://cloud.githubusercontent.com/assets/13786997/9297501/53d3ba5c-4455-11e5-9a6e-3764b758ef73.png)

**Comment by talonos2** [comment]
Great bug report. Fixed. Also fixes a similar issue with "assassin apparel".
