### ISSUE TITLE
Ship doors and elevators "Stuck open"

### ISSUE THREAD

**Issue by talonos2** [talonos2/BlightfallTracker#4]
As reported on IRC:

12:13 AM <dragonshardz> but both elevators are borked and the deck A door into the reactor is also borked
12:13 AM <dragonshardz> I'm betting it a busted circuit somewhere

**Comment by skittishtrigger** [comment]
deck a seems to be a circuit issue, but the buttons seem to be a perm/interact issue. if you op yourself from console you can click on them fine and deoping to normal borks them.

**Comment by talonos2** [comment]
The ones with the circuit issues are now fixed.

**Comment by talonos2** [comment]
All are now fixed.
