### ISSUE TITLE
Server crashes with Biomescanner / scanner.dat

### ISSUE THREAD

**Issue by bentalexanderhaase** [talonos2/BlightfallTracker#41]
We are currently hosting servers for the official Technic Blightfall pack that uses your mod. Because those servers are public ones we need some plugins for protection etc. So we need to use a version of KCauldron-1291(the same Forge version that the official Blightfall.jar has). Starting the server is impossible until you manually delete the scanner.dat file else you will get this http://pastebin.com/sPpWdXPJ NPE. After that the server starts and runs fine until someone clicks the Biomescanner block on the top which normally initiates the Biome-Scan for the world as far as I can see. This leads to the same crash (http://pastebin.com/sPpWdXPJ) that you get on the first start of the server that can only be fixed by deleting the scanner.dat file again. My guess would be that KCauldron (or Cauldron) handles the worlds biomes in a different way. Maybe it is possible to get some some magical try and catch block that deals with this ;)

Let me know if you need additional information!

Best regards,

**Comment by bentalexanderhaase** [comment]
I am sorry for this not being the most professional crash-report I am capable of ;) Quite in a hurry right now, so I just copied my report from the forums here.

**Comment by talonos2** [comment]
This has been brought to the attention of the modder that programmed the Biome scanner. Thanks for the report. No promises, but I hope we will be able to support KCauldron soon!

**Comment by bentalexanderhaase** [comment]
Thanks this sounds great! Let me know if you or the modder that programmed the biome scanner needs any additional information.

**Comment by talonos2** [comment]
We may have fixed it with this coming patch. Let us know if more problems arise.
