### ISSUE TITLE
Java 64 bit 32 bit issue

### ISSUE THREAD

**Issue by Chiefaruni** [talonos2/BlightfallTracker#45]
I am having issues with the 2gb of RAM issue, Ive installed the latest Java version 64 bit and still its telling me im using 1gb.

**Comment by Dunaka** [comment]
Is your windows version 32 bit or 64 bit?

**Comment by Chiefaruni** [comment]
64 Bit

**Comment by Messaika** [comment]
Delete all your java downloads, then install the 64 bit version.

**Comment by mattcloward** [comment]
One of my computers also has this issue. Even though you have 64 bit Java, if you computer doesn't have more than 2G of ram, there isn't enough to allocate. Realy frustrating :(

**Comment by talonos2** [comment]
I'm going to assume Messaika's comment fixed Dunaka's problem. If not, let me know.
