### ISSUE TITLE
Taint Spore Autopsy has incorrect description

### ISSUE THREAD

**Issue by Moleculor** [talonos2/BlightfallTracker#47]
Just killed a Taint SWARM (the bees). 

Taint SPORE Autopsy was completed, detailing how they burst open and spew out spiders.

These two things are not the same. I've never killed a spider egg thing.

**Comment by talonos2** [comment]
Killing a taint swarm does not unlock taint spore autopsy. I just tested it. 

I then killed a taint spore, and it _did_ unlock the autopsy. 

I'm gonna have to mark this as "Cannot reproduce," I'm afraid. :(

Taint spores look like little wiggling cubes. The bigger they get, the more spiders they spawn when you break them. If you break them while they are small enough, no spiders come out. Perhaps you accidentally broke one while fighting the swarm, but it was small enough you didn't notice?

Thanks for reporting, though!

**Comment by Moleculor** [comment]
Yup. Entirely possible I accidentally broke something without noticing. Everything's purple.
