### ISSUE TITLE
Teleport pads not working?

### ISSUE THREAD

**Issue by Blikjesman** [talonos2/BlightfallTracker#49]
Hello!

My friends and I stumbled upon this cool mod pack, got really excited to play and hosted a server..

Only to find out that the teleport pads that are supposed to teleport us to the world are not working for some reason? We have tryd several things but no idea why it is not working.

Can you help?
-Nivlek

**Comment by talonos2** [comment]
If you mean the little cubes in the drop pods, the most common reason for this is that command blocks are disabled in server.properties. Command blocks must be enabled for those teleporters to work.

If you mean the floating cube in the teleporter room across from the scanner room, that one only works _after_ going to a biodome.

**Comment by Blikjesman** [comment]
I mean the drop pods for wich biome you chose

**Comment by Blikjesman** [comment]
We will try checking that in the server properties! thanks! will give the results when we try it

**Comment by Blikjesman** [comment]
Works perfectly now! thanks!
