### ISSUE TITLE
World Crash on Load up

### ISSUE THREAD

**Issue by deth1999** [talonos2/BlightfallTracker#52]
Hi there Talonos! So when I go to play a singleplayer world, I hit play and then the screen comes up that says "loading terrain" and the client crashes and opens up the technic launcher... I think something that may have had a factor in this is that a couple days ago the game froze and to try to "jumpstart" the game and un freeze it by hitting ctrl+alt+del and launching the task manager. The task manager launched and the world crashed... This may just be a coincidence but I don't know... The crashlog is attached to this issue. http://pastebin.com/iy16qcqM

**Comment by talonos2** [comment]
Quick answer: World is corrupt. Not sure it can be recovered.

Nice answer: I _think_ this might be recoverable if you delete scanner.dat in the save directory. That's where it seems to be loading the data from, so if that's the corrupt file, deleting it and letting it regenerate might do the trick.

Hope it works. It'd be a real pain to lose your world. :(

Good luck!

**Comment by deth1999** [comment]
Thanks!
Lets hope I can save it, three days work at stake here... but then again it was mostly strip mining for about a stack of ores and a stack of double compressed cobble lol

**Comment by talonos2** [comment]
Please let me know how it goes.

**Comment by deth1999** [comment]
That solved the problem, thanks for your help! Its a really cool modpack, probably my favorite! really hit it out of the park on this one!

**Comment by talonos2** [comment]
Cool. Have fun!
