### ISSUE TITLE
Recipe Inconsistency

### ISSUE THREAD

**Issue by SephirothWS** [talonos2/BlightfallTracker#58]
![Image inside Edited Book](http://i.imgur.com/0qWUDHR.png)

---

![NEI Image 1](http://i.imgur.com/42IgIGY.png)
![NEI Image 2](http://i.imgur.com/WJAMHeO.png)

---

The main reason for opening this issue is the fact that you've taken it upon yourself to edit and split off mDiyo's books into your own. ... So why can't we reflect the updated (needlessly harder) recipes for the silky jewel inside the edited book? :P

**Comment by talonos2** [comment]
Cannot figure out how to fix this. I do not specify the recipe in the manual; it should be getting the recipe automatically from the recipe registry. Thing is, it's getting the old recipe, not the new one. Perhaps the manual is loading before iguana tinker tweaks is? And then caching it incorrectly?

To make things less confusing, at least, I deleted the two inconsistent pages. People know how to use NEI. If they want a silky jewel and don't know how to make it, they'll figure it out.
