### ISSUE TITLE
Can't smelt flour into bread in Redstone Furnace

### ISSUE THREAD

**Issue by SephirothWS** [talonos2/BlightfallTracker#59]
... Exactly as the tin says. Can't smelt flour into bread in a Redstone Furnace. Doesn't allow me to place the flour into the input slot.

**Comment by talonos2** [comment]
This is annoying, and stems from Thermal Expansion's caching scheme. I can hard-code add this recipe with MineTweaker, but there's no general fix that guarantees that the redstone furnace will always line up with the vanilla furnace.
