### ISSUE TITLE
Can't download it...

### ISSUE THREAD

**Issue by royfire1230** [talonos2/BlightfallTracker#60]
When i download it, In the middle of Libraries it stops and then it says:
Failed to download a file for the following pack: Blightfall

Failed to download:https://libraries.minecraft.net/org/scala-lang/scala-actors/2.11.6/scala-actors-2.11.6.jar

Please consult the modpack author.

Hoping to get a response from you guys...

**Comment by talonos2** [comment]
This is a problem with Mojang's library servers. It'll work again once they fix their servers. Until then, there's nothing we can do. :/ Try redownloading in an hour or so?

**Comment by royfire1230** [comment]
A thank god, I thought i couldn't play it.

**Comment by royfire1230** [comment]
nope, still not workin :(

**Comment by bochen415** [comment]
working fine here right now, maybe you have security software blocking it @royfire1230

**Comment by royfire1230** [comment]
Nope

**Comment by royfire1230** [comment]
I've tried again and still it doesn't work, Can you guys send me the mod through dropbox or mega?

**Comment by bochen415** [comment]
It's not a mod, it's a library. Post launcher logs from .technic/logs get the newest file. Use pastebin.com.

**Comment by royfire1230** [comment]
http://pastebin.com/FJ26d6tG

**Comment by bochen415** [comment]
Try [this](http://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.11.6/scala-actors-2.11.6.jar).
Download it to .technic/cache/org/scala-lang/scala-actors/2.11.6/
