### ISSUE TITLE
Add key to front door of obsidian tower

### ISSUE THREAD

**Issue by flowtender** [talonos2/BlightfallTracker#61]
(Feature Request)

Either as a drop from the boss, or in a chest in an inaccessible location. In case players want to make this place their new home.

**Comment by dashkal16** [comment]
+1 on this.  After taking position of the tower, I'd like to make it into my magic base.  I can of course just ignore the front door, but it 'feels better' to take the keys to my new tower.

**Comment by talonos2** [comment]
Okay. We'll see what we can to to make it happen next update.
