### ISSUE TITLE
Can't Open Quest Book

### ISSUE THREAD

**Issue by Messaika** [talonos2/BlightfallTracker#62]
I really don't understand why this isn't working.......

**Comment by talonos2** [comment]
Your questbook will not open if there is a discrepancy between your quests and the quests on your server. Probably either you updated but your server didn't, or the other way around.

Does this happen in singleplayer? If so, we have a problem. Otherwise, there's not much I can do.

**Comment by Messaika** [comment]
Yeah, it was a server/player version discrepancy. Just had to roll back. Hopefully Apex will add the new update soon.
