### ISSUE TITLE
Cooking For Blockheads I lists 'Toast Sandwich' as valid recipe when it is not.

### ISSUE THREAD

**Issue by Moleculor** [talonos2/BlightfallTracker#66]
Just like it says on the tin. If you have multiple Toast in your inventory, reading Cooking For Blockheads I will list a 'Toast Sandwich' (made with two pieces of toast) as a viable cooking option, when it is not one.

**Comment by talonos2** [comment]
How embarrassing.

CanVox had to hack in a fix for this. Luckily Cooking for Blockheads is a MIT-licensed mod.
