### ISSUE TITLE
Mousewheel counts as clicking on Cooking Table

### ISSUE THREAD

**Issue by caysyka** [talonos2/BlightfallTracker#67]
Scrolling the mouswheel counts as a normal click in the Cooking Table from Cooking for Blockheads, causing you to craft a lot of food instead of scrolling.

**Comment by caysyka** [comment]
Upon further testing, this only applies to scrolling up, not down.

**Comment by talonos2** [comment]
This is a problem with the interaction between mouseTweaks and Cooking for Blockheads. He says he's looking into a fix: https://github.com/blay09/CookingForBlockheads/issues/46 With any luck, we'll be able to pull that in when he finishes.
