### ISSUE TITLE
Cooking Table incompatible with Vanilla double chests

### ISSUE THREAD

**Issue by caysyka** [talonos2/BlightfallTracker#68]
The cooking table from cooking for blockheads only reads inventory from half of a double chest that it is connected to. Double(tall) lockers from Better Storage work fine, though.

**Comment by talonos2** [comment]
Out of our hands, but he says he's fixing this in the next version. https://github.com/blay09/CookingForBlockheads/issues/45

We might update then, especially if he adds minetweaker support in a way that isn't a gross hack (Like we're about to do.)
