### ISSUE TITLE
World wont load

### ISSUE THREAD

**Issue by chrissquest** [talonos2/BlightfallTracker#70]
So I updated to the new version and now my new and old worlds wont load. it starts loading terrain and then goes back to the title screen. it usually flickers the tite screen but this time it stays on it. Heres the log: http://pastebin.com/fNB26Dp6 but I don't know if it will help. Another thing to note, the game still runs in the background when I quit it, so I have to force close it.I already tried re installing so that doesn't help D=

**Comment by gorgonfiredotcom** [comment]
I had the same issue as well as others which I will post in another issue

**Comment by talonos2** [comment]
I am not seeing a crash on here. Try sending me the FML-server-latest log?

**Comment by chrissquest** [comment]
I don't see a server log... This is in singleplayer. If there is something like that, were can I find it?

**Comment by chrissquest** [comment]
heres the client log if that is what you meant:https://www.zerobin.net/?aa2626375f0bc4cd#xk80f71YJf+UUDHHMBw9LfmzTwVvzx6bsNHP+5YbHjQ= (paste is too big for pastebin)

**Comment by chrissquest** [comment]
right before it starts to stop in the log it says something about ender storage not being in gzip format. but I have no idea what that means:http://pastebin.com/kNMkHWaC

**Comment by chrissquest** [comment]
ok so it works =D. deleting enderstorage did it! hope that wasn't important. I might try updating it later. and see if it works
