### ISSUE TITLE
gltich death?

### ISSUE THREAD

**Issue by squidlet918** [talonos2/BlightfallTracker#71]
Good morning. So, I drove my boat from the Omega Bio-dome to the east side of the glacier island, got out of my boat to get on the ice, and it acted as if I was stuck in some thing (like when sand falls on you, and you're stuck in the wall.) and killed me. I'm not sure if this was supposed to happen of not, I may have found a glitch. Please inform me if this was a glitch or if I froze to death. Thank you. -Squid

**Comment by talonos2** [comment]
That was a glitch. There is no freezing to death mechanic in the game.

Sorry for your loss. It's things like this that makes me glad I turned
"KeepInventory" on in this version.

**Comment by talonos2** [comment]
Were you on a server when this happened?

**Comment by squidlet918** [comment]
I was in single player in the new Blightfall mod. You keep your inventory, but you lose points. There's a quest from "The Instructor" called "Un-die", where if you feel like you died because of a glitch you receive a piece of "Nether Rutile Ore" and receive your points back. I'm not sure how to report the problem except here. I mainly just wanted to see if this was a recurring problem/glitch or not. Thanks for the confirmation though ;p. -Squid

**Comment by mattcloward** [comment]
Most likely a boat location de-sync issue. It's a bug with Minecraft boats, not a Blightfall issue, where the location of boats on client and server sides don't match. I bet you got out and got stuck in the ice.

**Comment by squidlet918** [comment]
Ah, I see. Well, at least i know not to get out of my boat in that area :). Thanks for the response. Ill let you know if i have any other issues. Thanks again! -Squid
