### ISSUE TITLE
Loading issues with server and world

### ISSUE THREAD

**Issue by gorgonfiredotcom** [talonos2/BlightfallTracker#72]
I had a server just for me and a couple friends using Logmein Hamachi on Blightfall 2.1.0 but when the update came out (I didn't even update my client or server) my server started saying that it was in an incorrect state when I tried to launch it and closing without an error report. I put the world in my saves folder and tried to open it in single player and it brought me back to the title screen after trying to load it. I tried replacing the files from the 2.1.0 server zip and the same thing happened with that world and when I tried it with the world that it comes with, my Minecraft crashed when I tried to log in (the server and my client said that I had logged in but that the connection had been forcibly terminated). I even tried updating both my server and client but the exact same things happened.

**Comment by talonos2** [comment]
I'd suspect your world is corrupt somehow. Could I get a pastebin of your server's crash report?

**Comment by gorgonfiredotcom** [comment]
It discarded it...

**Comment by gorgonfiredotcom** [comment]
I have the crashed server up now if you want the last things it said?

**Comment by gorgonfiredotcom** [comment]
there's still the problem of the new world crashing my client whenever I log in to the server

**Comment by talonos2** [comment]
Yes, please. I'll need that crash report.

**Comment by gorgonfiredotcom** [comment]
http://pastebin.com/HcfrKpa0
That's not a crash report but that's all I've got

**Comment by talonos2** [comment]
No, you definitely have a crash report, you don't know where it is. It should be in your modpack directory under "Crash reports". This looks like the tail end of a crash report, copied from the console. The stack trace near the beginning of a crash report is the most helpful part, and this report is missing it.

**Comment by gorgonfiredotcom** [comment]
oh the one with the client crashing when I log in? That's here: http://pastebin.com/LavtNBPn
With the world that you believe to be corrupted, that not only said it may have discarded it but also didn't put a crash report in the crash reports folder for the server
Also it seems to work now.

**Comment by gorgonfiredotcom** [comment]
So apparently if I open the old world bringing me to the title screen without launching the world then it crashes my game.  You know, if that helps.
