### ISSUE TITLE
Terrestrial Nether Quartz won't spawn. Intended?

### ISSUE THREAD

**Issue by NEckes** [talonos2/BlightfallTracker#73]
The Users on our Servers asked us about the missing Terrestrial Nether Quartz. Intended?

**Comment by talonos2** [comment]
Let me run around with my X-ray mod on and see if I can spot it.

**Comment by talonos2** [comment]
Nope, it's totally spawning.
![2015-08-21_15 40 49](https://cloud.githubusercontent.com/assets/3359830/9419731/8053e4d4-481b-11e5-97c6-0b3ecb2f2d63.png)
![2015-08-21_15 41 45](https://cloud.githubusercontent.com/assets/3359830/9419734/86fcf370-481b-11e5-8469-1d04278676f7.png)
