### ISSUE TITLE
Armor Status HUD & Blood Magic HUD overlap

### ISSUE THREAD

**Issue by SephirothWS** [talonos2/BlightfallTracker#77]
Pictures are better than words.

---

![Without Chat Open](http://i.imgur.com/SGH5mbj.png)
![With Chat Open](http://i.imgur.com/l8B4xeC.png)

---

Basically we need Armor Status HUD to be shifted down a bit more so people getting into Blood Magic like myself can see the soul network gauge that'll be up in the top left of the screen without it being overlapped by Armor Status HUD.

**Comment by Scorch-Mechanic** [comment]
You can fix this yourself by opening Mod Options, selecting Armor Status Hud, clicking Config, and altering the HUD offsets. Or by changing the location of the HUD itself (I like mine on the right side myself).

**Comment by SephirothWS** [comment]
The idea of having this -fixed- in the configs shipped with the pack is so people don't have to do the steps you laid out -each and every time- there is an update.
