### ISSUE TITLE
need a little help here!

### ISSUE THREAD

**Issue by DeBobbel** [talonos2/BlightfallTracker#79]
if i make a world, it isn't hardcore, and a cant complete some quest in that mode!!!
This bugg for my RUINE the modpack.
also i don't have permission to set my world on hardcore by the command /hqm hardcore.
can you guy(s) please help
- Bjornkok

**Comment by talonos2** [comment]
Questing mode is enabled by default. "Hardcore Questing" mode is disabled by default, so your world does not get deleted when you run out of lives.

What quests, specifically, are you unable to complete?

**Comment by DeBobbel** [comment]
1. i realy want to go hardcore with lives, can you please help my.
2. the quest that you bring 1 normal bread, and some others
3. Archimedes' Ships mod is also in the modpack, i can make everyting accept the ship helm (control panel) i use the crafting recipe: wood stick wood
                                                  stick  iron  stick
                                                  wood stick wood

**Comment by talonos2** [comment]
1: Remember how you used to have to buy extra lives for 10 reputation each? Well, now, every time you die, 10 reputation is automatically deducted from your total. To simulate "hardcore with lives", delete your world if you ever go below -30 reputation.

2: The quest where you give normal bread, you must give the kind of bread where you make flour out of wheat and a mortar and pestle, then cook the flour in a furnace. Bread make from lining up three wheat on a crafting table will not work.

**Comment by talonos2** [comment]
3: In archimedes ships, the ship helm is now an infusion recipe. Research it with Thaumcraft. (It'll be in the artifice tab after you discover infusion crafting) There's also a free ship helm somewhere in the world you can plunder.

**Comment by DeBobbel** [comment]
ok thx :D
now 1 little question over, if i download the server.
make a folder, put everyting on it, confirm ealu etc, op the server, it work, butt it skips somethings
so i dont have quests i spawn random, i dont have the mods etc, i think its the ram for the server, could you please help. send a video or something else.
- Bjornkok
  (if i do something wrong, explane it please)

**Comment by talonos2** [comment]
You are running minecraft-server.jar. Instead, run start.bat or start.sh.
