### ISSUE TITLE
Error loading DawnMachine.zs script; DawnMachine item 1896 has broken texture

### ISSUE THREAD

**Issue by zhukant** [talonos2/BlightfallTracker#8]
Summary: [Mac OSX Yosemite 10.10.4]
With a clean install of the Technic Launcher, no other modpacks installed. Upon creating new world and subsequently upon logging into SSP on the same world, receive error message as follows:

"ERROR: Error loading DawnMachine.zs: stanhebben.zenscript.parser.TokenException: Invalid character at DawnMachine.zs:10 - [?]"

Where [?] is a placeholder for a missing unicode character displayed as a box with a question mark inside.

Upon further investigation, conducted a search for DawnMachine using NEI's recipe mode and discovered that the item numbered 1896 has a missing texture represented by black and purple checkerboard pattern. The other four Dawn Machine items had the correct texture.

Repro Steps: 
1. Install Technic Launcher on Mac OSX Yosemite 10.10.4
2. Install BlightFall modpack
3. Enable 2GB Java
4. Launch ModPack and create new world in Survival Single Player.
5. Error appears in internal chat dialog.

Logs:

The following is a link to a copy of my local DawnMachine.zs file on Dropbox. An administrator on the IRC chat for Technic has already verified the file is identical to the original file and he and other users attested that it functions properly in other circumstances.

https://www.dropbox.com/s/t49muw4blx5kf76/DawnMachine.zs

The following are the only two log entries in the launcher log that ever occur which mention the topic:

[B#313] 2015/08/12 23:05:19 [INFO]  [23:05:19] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:152]: MineTweaker: Loading DawnMachine.zs
[B#313] 2015/08/12 23:05:30 [INFO]  [23:05:30] [Client thread/INFO]: [CHAT] ERROR: Error loading DawnMachine.zs: stanhebben.zenscript.parser.TokenException: Invalid character at DawnMachine.zs:10 - �

These recur every time the world is loaded. The full log entry is linked to on Dropbox below.

https://dl.dropboxusercontent.com/u/5853323/techniclauncher_2015-08-12.log

**Comment by talonos2** [comment]
Could you do me a favor?

In Dawn Machine.zs, I use the § character. To my knowledge, this file is the only place I use it for thaumcraft research. I suspect that macs are having problems with this file, though I wouldn't know why.

Could you try opening up Dawn Machine.zs and trying to delete all the § characters, then try to run it again and see if the error goes away? If so, I think we will have nailed it.

I lack a mac, so I can't test this myself. Sorry. :(

**Comment by zhukant** [comment]
Thank you for your prompt reply! I really appreciate the help and advice I've been receiving - I wish things were this awesome for services I actually pay lots of money for. 

Could you advise regarding which application you are using to edit the file? I have opened it in Mac's native Text Edit application as well as Microsoft Word and in both cases I wasn't able to find a single instance of the character. 

Here's a screenshot of the text editor. You can see I performed a search for the character at the top. The entire text doesn't fit on the screen, but there are only a few lines that are obscured by the bottom of the screen.

https://www.dropbox.com/s/iujd1qi8ihkvdy8/Screenshot%202015-08-13%2015.31.06.png?dl=0

Is this similar to what you see? Perhaps the character is rendering as a different one.

**Comment by talonos2** [comment]
Weird. Yeah, this is definitely an encoding problem of some sort, and is only affecting macs as far as I can tell.

http://i.imgur.com/MkyGu8o.png

Keep playing. In our bugfix update a week from now, we'll release a patch of some sort for it, but you're a long way off from the dawn machine, so it shouldn't cause a problem until then.

**Comment by skittishtrigger** [comment]
I would like to confirm that this issue is present on winblows 7 64bit also. HIt me up here or ping me on #technic if you need any info. same scenario btw. fresh server install/client install. also tried it on a win8 machine with same results.

**Comment by jesmores** [comment]
This is happening on a server install (Apex Minecraft Hosting). Can confirm that deleting the § character makes the error go away.

**Comment by talonos2** [comment]
Well okay. I'll fix that next version then.

I wonder why this doesn't happen on my computer...

**Comment by jesmores** [comment]
I may have fixed it ... open the DawnMachine.zs script in a decent text editor and save it with UTF-8 encoding. I'm not sure if it -actually- fixes it, since I don't have those pages yet (still early in the game) but it does make the error go away.

**Comment by talonos2** [comment]
Gonna try that. Thanks for the heads up. This would also explain why it sometimes seemed OS dependent, but not entirely, and happened more frequently to macs and Linux machines than to PCs. I bet in my windows locale it works, but in other locales it does not.

I wish I knew everything about computers. That would make life easier.
