### ISSUE TITLE
Scout quest-line not accesable

### ISSUE THREAD

**Issue by gorgonfiredotcom** [talonos2/BlightfallTracker#87]
I started a new server world after my old one was corrupted (again) and went to biodome epsilon, then registered as team epsilon in the scout questline, my friend accidentally went to biodome gamma, and registered as team gamma in the scout questline.  We both joined a party and now neither of us can access the scout questline.

**Comment by talonos2** [comment]
This is a known issue with HQM. The devs refuse to continue supporting it, and it is closed source, so we cannot fix it ourselves.

Only join teams with those in your own biodome, or it will lock the scout questline.
