### ISSUE TITLE
Royal Jelly removed? 

### ISSUE THREAD

**Issue by LordQ42** [talonos2/BlightfallTracker#88]
I found, in one of the villages, a bunch of queen bees. I set up a small apiary and when the bees were too tired to be useful any more, I was going to turn them in to royal jelly to start a new generation from the grubs. However, when I try to put my 0 durability queen bees through the wringer for royal jelly, nothing happens. (that is, the recipe doesn't seem to exist?) were bees and honey supposed to be disabled or did I miss something else?

**Comment by talonos2** [comment]
I meant to re-enable that recipe. Expect it to be back next version.
