### ISSUE TITLE
Tar cannot be used for Thaumcraft labels.

### ISSUE THREAD

**Issue by Krakatoah** [talonos2/BlightfallTracker#91]
Currently you cannot make thaumcraft's jar labels using Tar, you can only use Green Slime and Glue.

![ss 2015-08-24 at 04 20 55](https://cloud.githubusercontent.com/assets/13937436/9432577/109c489e-4a1d-11e5-9126-57a7579dc5a4.png)

**Comment by talonos2** [comment]
Fixed. Now you can use every oredict slimeball _except_ blood. I'm not budging on that one.
