### ISSUE TITLE
Blightfall v2.1.2

### ISSUE THREAD

**Issue by SniketTheLlama** [talonos2/BlightfallTracker#94]
I have been hosting a server since v2.1.0. Never had any issues. Once v2.1.2 came out, I decided to create a new folder to test the implementation of the new version. It loaded up great. The issue was that the player profiles were kept in regards to the teams each player were on along with the free box of food from the captain. I removed all instances of the v2.1.2 server and started fresh once again. This time, it will not load. I am met with a crash. You will find the details below. 

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 8/24/15 12:01 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Duplicate enchantment id! class thaumic.tinkerer.common.enchantment.EnchantmentPounce and class net.mcft.copy.betterstorage.item.EnchantmentBetterStorage Enchantment ID:170
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
    at thaumic.tinkerer.common.enchantment.EnchantmentMod.<init>(EnchantmentMod.java:26)
    at thaumic.tinkerer.common.enchantment.EnchantmentPounce.<init>(EnchantmentPounce.java:8)
    at thaumic.tinkerer.common.enchantment.ModEnchantments.initEnchantments(ModEnchantments.java:56)
    at thaumic.tinkerer.common.core.proxy.TTCommonProxy.init(TTCommonProxy.java:102)
    at thaumic.tinkerer.common.ThaumicTinkerer.init(ThaumicTinkerer.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1953453488 bytes (1862 MB) / 2485125120 bytes (2370 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -Xmx3G -Xms2G -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 101 mods loaded, 101 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.85.1291} [Forge Mod Loader](Blightfall.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.2.1291} [Minecraft Forge](Blightfall.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    blightcore{1.2.0} [Blight Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    newradicalbotany{1.1.2} [New Radical Botany](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    notimefix{2.1.0} [No Time Fix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PlayerAPI{1.4} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv2-stable-1} [Applied Energistics 2](appliedenergistics2-rv2-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-268.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Automagy{0.24.1} [Automagy](Automagy-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    betterrain{0.15} [Better Rain](betterrain-1.7.2-1.7.10_0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.10.3} [BiblioCraft](BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-0.3.2.jenkins186} [Mantle](Mantle-1.7.10-0.3.2.jenkins186.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BigReactors{0.4.1A2} [Big Reactors](BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.6-191} [Botania](Botania r1.6-191.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cookingbook{1.0.0} [Cooking for Blockheads](cookingbook-mc1.7.10-1.0.54-mt3hack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    customnpcs{1.7.10c} [CustomNpcs](CustomNPCs-1.7..10c-herohack2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.1.321} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.2.5} [Extra Utilities](extrautilities-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} [Tinkers' Construct](TConstruct-1.7.10-1.8.3-RFNerf.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy{4.0.5} [Metallurgy 4](Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.10g} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-471.jar) Unloaded->Constructed->Pre-initialized->Errored
    ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreQuesting{The Journey (4.2.3)} [Hardcore Questing Mode](HQM-The Journey %284.2.3%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized
    modelcitizens{1.0.1} [Model Citizens](ModelCitizens-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    modtweaker2{0.7} [Mod Tweaker 2](ModTweaker 2-0.7.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Netherless{0.9.0} [Netherless](Netherless-0.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    purplepanic{1.0.1} [Purple Panic](purplepanic-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized->Initialized
    biomescanner{0.1.0} [Biome Scanner](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    blightbuster{0.1.0} [BlightBuster](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cavestokingdoms{0.0.1} [Caves to Kingdoms](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RPGAdvMod{1.0.0} [RPGAdvMod](RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Schematica{1.7.5.git} [Schematica](Schematica-1.7.10-1.7.5-GenHack2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SpiceOfLife{1.2.4} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StorageDrawers{1.7.10-1.5.3} [Storage Drawers](StorageDrawers-1.7.10-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TabulaRasa{1.7.10R1.0.1} [Tabula Rasa](TabulaRasa-[1.7.10]1.0.1-3-Blight3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    playerzombiemod{v1} [Tainted Players](TaintedPlayers-v1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TerrainControl{2.7.0-SNAPSHOT} [Terrain Control](terraincontrol-forge-2.7.0-colored-lockhack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumicenergistics{0.8.10.6} [Thaumic Energistics](thaumicenergistics-0.8.10.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0RC7-98.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TiCTooltips{1.2.4} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TML{3.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-3.0.1.B22-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    UndergroundBiomes{0.7} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-test41.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ubcores{1.7.10-0.1.2.0} [UBC Ore Registrar](UBCOres-1.7.10-0.1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.1.321} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HungerOverhaul{1.7.10-1.0.0.DEV.c9b8cee} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0-ConfigHack-2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IguanaTweaksTConstruct{1.7.10-2.1.4.DEV.0edeedd} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.4.DEV.0edeedd.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.1.321} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-268
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    TConstruct Environment: Environment healthy.
    NetherOres: Lacking version information.
    RedstoneArsenal: -[1.7.10]1.1.0-80
    ThermalDynamics: -[1.7.10]1.0.0RC7-98
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by talonos2** [comment]
It seems the configs did not get copied over correctly. The enchantment IDs
it is complaining about have been around since 2.0.4e, and have not
changed. Try deleting the config directory and replacing it with the config
directory from a fresh 2.1.2 server.

**Comment by SniketTheLlama** [comment]
That did not work for me. I even tried copying over the config folder from my v2.1.0 server. No such luck.

**Comment by SniketTheLlama** [comment]
I managed to get the server up and running. It was an issue on my end. My antivirus/firewall does something different with new files that was messing things up. Without going into much detail, I was able to get it working with my antivirus/firewall configurations. Now to attempt getting my information carried over from my old server.

**Comment by talonos2** [comment]
Copying the config file over from a 2.1.0 will will cause many other
issues. The best way to update is to take a clean 2.1.2 server, delete the
world folder, and then paste in the world folder from your old server.

Hope that helps.

**Comment by SniketTheLlama** [comment]
No luck. I copied over my old world after deleting the v2.1.2 world and it seems the fresh v2.1.2 install is connected to the v2.1.0 information in regards to my character talking to the captain and already being a part of team Alpha. The other information has been wiped. Everything I built, everything I had in my inventory, not there. Could this be in a temp folder somewhere?

# UPDATE

I managed to finally get the player profile working. All my inventory is there. The world, however, is a different story. It's a new world. Everything I had built in my v2.1.0 server is not in my v2.1.2 server.

**Comment by talonos2** [comment]
I am sorry. I have heard of many people updating to 2.1.2 without a problem. As mentioned above, you should be able to take a clean 2.1.2 server, delete the world folder, and then paste in the world folder from your old server. Without looking at exactly how you have your server set up, I don't think I can help you. :(
