### ISSUE TITLE
Party Quest Book Bug

### ISSUE THREAD

**Issue by gregoryw3** [talonos2/BlightfallTracker#95]
After completing a portion of the book then joining a party through the quest book, the quest book deletes most of the quests and the remaining quests were prematurely unlocked and the starting quests says we finished them but they won't show the rest of the quest line.

**Comment by gregoryw3** [comment]
Update,
By the way the party was Team Alpha and we have gone down the Alpha drop.

**Comment by talonos2** [comment]
The description of the bug is kind of vague, but if I understand it correctly, this is a known issue with HQM and is out of our control. It's complicated, but I guarantee that If you form parties before dropping, this should not happen.
