### ISSUE TITLE
Metals Don't Have Nugget Forms

### ISSUE THREAD

**Issue by mattcloward** [talonos2/BlightfallTracker#96]
Almost all ores from the metallurgy mod, excluding copper and tin, lack nugget forms, making removing them from the smeltery impossible. If you have any control over this, it would be a nice fix.

**Comment by talonos2** [comment]
It would be very difficult to make this work, involving many, many lines of
minetweaker code. Perhaps in the future.

Until then, note that you can pour metals into a Thermal Expansion portable
tank for temporary storage. In fact, if you use a servo and fluiduct to
pipe fluid into a smeltery drain, you can even put them back _in_ the
smeltery later.

**Comment by mattcloward** [comment]
I figured it would be difficult to fix. Thanks for the tip!
